Feature/baomt/t03 add pagination
fabatek/onboarding-job-board-frontend pull request #103
Opened 2023-03-17 03:16 UTC by tminhbao

2023-03-17 04:00 UTC, Tiencmfaba requested changes

2023-03-17 04:43 UTC, tminhbao commented on src/components/Pagination/Pagination.tsx
> +  console.log("pagination-re-render");
Fixed

2023-03-17 04:52 UTC, tminhbao commented on src/components/Pagination/Pagination.tsx
> +  }
Fixed

2023-03-20 03:12 UTC, TruongNP approved these changes

2023-03-20 03:22 UTC, merged