Task t01 - Show the total numbers of jobs
fabatek/onboarding-job-board-frontend pull request #29
Opened 2021-09-21 02:38 UTC by TanDangNgoc

Note:
1. Using bootstrap for styling header
2. Call API from mockAPI and show the total numbers of jobs are available
![image](https://user-images.githubusercontent.com/91040454/134103061-d939385a-ee60-411c-8472-dd9e9d088e98.png)

2021-09-22 07:22 UTC, hienntfaba requested changes

2021-09-23 06:37 UTC, TanDangNgoc commented on src/containers/Home/component/SearchBox/index.tsx
> +        <div className='searching_box bg-dark text-white container-fluid' data-testid='searching_box'>
changing className due to BEM
![image](https://user-images.githubusercontent.com/91040454/134463915-e91d7c7b-b072-4f4e-80fd-8b9e50ffbd49.png)

2021-09-23 06:39 UTC, TanDangNgoc commented on src/containers/Home/index.tsx
> +        const handleGetData = async () => {
Moving callAPI function to store
![image](https://user-images.githubusercontent.com/91040454/134464017-b88b8d93-c3d8-4e15-b83c-87a1f40213ed.png)
![image](https://user-images.githubusercontent.com/91040454/134464138-85d7bf94-1713-42dc-b127-728c812b1122.png)

2021-09-23 06:40 UTC, TanDangNgoc commented on src/containers/Home/component/Result/Result.tsx
> +const Box:React.FC<PropsBox> = ({title, company, available, position, location, salary}) => {
Changing list of props to Job props
![image](https://user-images.githubusercontent.com/91040454/134464260-e6425138-69d2-4f2a-9319-2a2c67586957.png)

2021-09-23 06:41 UTC, TanDangNgoc commented on src/containers/Home/component/Result/result.test.tsx
> +    expect(tree).toMatchSnapshot()
Testing data is available
![image](https://user-images.githubusercontent.com/91040454/134464439-3cf7ac1d-f54a-4eb5-8933-e2c38bdd90e8.png)

2021-09-23 06:43 UTC, TanDangNgoc commented on src/containers/Home/component/Jobs.ts
> +    Available: boolean;
Adding key as string
![image](https://user-images.githubusercontent.com/91040454/134464548-9844210d-a575-4cd5-8953-bb6804fb6b2f.png)

2021-09-23 06:52 UTC, hienntfaba commented on src/containers/Home/index.tsx
> +        const handleGetData = async () => {
Good work!

2021-09-23 07:28 UTC, TanDangNgoc commented on src/containers/Home/component/Jobs.ts
> +    Available: boolean;
Changing keyword
![image](https://user-images.githubusercontent.com/91040454/134469358-47629469-f137-4e59-94b5-280f79470ba2.png)

2021-09-23 07:44 UTC, TanDangNgoc commented on src/containers/Home/component/Jobs.ts
> +    Available: boolean;
camelCase keyword
![image](https://user-images.githubusercontent.com/91040454/134470136-3e2d353a-deb0-449a-b7d8-d264b60f3732.png)

2021-09-23 07:45 UTC, TanDangNgoc commented on src/containers/Home/component/SearchBox/index.tsx
> +        <div className='searching_box bg-dark text-white container-fluid' data-testid='searching_box'>
Edit className 
![image](https://user-images.githubusercontent.com/91040454/134471259-36905c00-0264-47ce-af1d-9c24d2ebfe01.png)

2021-09-23 07:52 UTC, hienntfaba approved these changes

2021-09-23 07:52 UTC, merged