Feature/chientv/t02 display the first 100 jobs
fabatek/onboarding-job-board-frontend pull request #75
Opened 2022-03-24 07:05 UTC by ChienVan01

Story:
Link code feature: https://github.com/fabatek/onboarding-job-board-frontend/tree/feature/chientv/t02_display_the_first_100_jobs
Link API to see specific job totals: https://6239311d043817a543df0a3f.mockapi.io/api/jobs
Link deloy: https://delirious-seat.surge.sh/

Notes

1. Edit JobList componenet: Map data from API to view

Result
![image](https://user-images.githubusercontent.com/85722847/159860576-84c15716-81aa-462b-95e5-5ef1653712e3.png)
![image](https://user-images.githubusercontent.com/85722847/159860657-30959a1d-001e-4407-82b9-c58dd135079c.png)
![image](https://user-images.githubusercontent.com/85722847/159860705-9d382041-80e1-4078-a11a-6661a46d7894.png)

2022-03-24 09:01 UTC, ChienVan01 commented
> 

done

2022-03-25 03:21 UTC, ducdmfaba requested changes
![image](https://user-images.githubusercontent.com/67683518/160047747-dc967c34-9ad4-436c-bb87-962a17d05879.png)

- Should have padding for section
- The item is too big
- Between items should have a margin

2022-03-25 03:21 UTC, ducdmfaba commented on src/components/jobList/JobList.tsx
> +            <div className='card w-25 p-3 '>
Missing key

2022-03-25 07:39 UTC, ChienVan01 commented
> ![image](https://user-images.githubusercontent.com/67683518/160047747-dc967c34-9ad4-436c-bb87-962a17d05879.png)
> 
> * Should have padding for section
> * The item is too big
> * Between items should have a margin

done

2022-03-25 08:36 UTC, ducdmfaba commented
Is it changed? I see nothing

2022-03-25 08:39 UTC, ChienVan01 commented
> Is it changed? I see nothing

Sorry, I have updated again!

2022-03-28 07:04 UTC, ducdmfaba requested changes

2022-03-28 07:04 UTC, ducdmfaba commented on src/components/header/header.scss
> +    padding-right: 50px !important;
It should be `padding: 20px 50px 0 50px;`

2022-03-28 07:04 UTC, ducdmfaba commented on src/components/jobList/jobList.scss
> +    padding-right: 0px !important;
Same above.

2022-03-28 07:04 UTC, ducdmfaba commented on src/components/seachContainer/searchContainer.scss
> +    padding-right: 0px !important;
Same above

2022-03-28 07:26 UTC, ducdmfaba approved these changes

2022-03-28 07:26 UTC, merged