[T02]: Display the first 100 jobs
fabatek/onboarding-job-board-frontend pull request #76
Opened 2022-03-24 07:59 UTC by MinhPhuongK57

**Stories:** 
Link code feature: https://github.com/fabatek/onboarding-job-board-frontend/tree/feature/phuongtm/t02_display_the_first_100_jobs
Link deploy surge: http://job-board-phuongtm.surge.sh/
Link API to see specific job totals: https://62346cbddebd056201e4b2c9.mockapi.io/api/jobs

**Notes:**

1. Add style in file jobcomponent.scss
2. Map data: Show display the first 100 jobs
3. File JobsList import JobComponent

**Result:**
![image](https://user-images.githubusercontent.com/81628154/159869113-d0a1d234-7fce-4ff2-9cd3-c92dd0bd3e9d.png)
![image](https://user-images.githubusercontent.com/81628154/159869157-7b3eea1f-e93e-4ade-a8e4-ac1fbb0a14eb.png)

2022-03-24 08:45 UTC, ducdmfaba requested changes

2022-03-24 08:45 UTC, ducdmfaba commented on src/containers/JobComponent/JobComponent.tsx
> +        {jobs.map((job: any) => {
Please use generic data type.

2022-03-24 08:45 UTC, ducdmfaba commented on src/containers/JobComponent/JobComponent.tsx
> +                  <input
Why did you use `input` tag instead `img`?

2022-03-24 08:45 UTC, ducdmfaba commented on src/containers/JobComponent/jobcomponent.scss
> +.card-custom {
Please follow BEM convention.

2022-03-24 08:45 UTC, ducdmfaba commented on src/containers/JobList/JobList.tsx
> +import JobComponent from "../JobComponent/JobComponent";
Please rename file `JobComponent.tsx` to `index.tsx`. It will make this shorter. Change all of the other places

2022-03-24 08:46 UTC, ducdmfaba requested changes
![image](https://user-images.githubusercontent.com/67683518/159877357-374f6f1e-9372-410f-8a0d-62186aaf86e0.png)

The image has stretched. Try to use `object-fit`

2022-03-24 08:50 UTC, ducdmfaba requested changes

2022-03-24 08:50 UTC, ducdmfaba commented on src/containers/JobComponent/JobComponent.tsx
> +                      {status === 1 ? (
The `status` has data type is `string`. Is this comparison correct?

2022-03-25 03:29 UTC, ducdmfaba requested changes
Please change all the names of custom classes following BEM convention.

2022-03-25 03:30 UTC, ducdmfaba commented
![image](https://user-images.githubusercontent.com/67683518/160048862-ebee2bc7-7ed2-4f1d-8d97-dc34dede9f0d.png)

Is this fixed? I still see it stretched

2022-03-25 07:27 UTC, MinhPhuongK57 commented
> ![image](https://user-images.githubusercontent.com/67683518/160048862-ebee2bc7-7ed2-4f1d-8d97-dc34dede9f0d.png)
> 
> Is this fixed? I still see it stretched

I fixed that but forgot to deploy again.
I'm sorry.

2022-03-25 08:28 UTC, ducdmfaba approved these changes

2022-03-25 08:37 UTC, merged