feat(#t04): search job by title
fabatek/onboarding-job-board-frontend pull request #81
Opened 2022-03-30 03:30 UTC by ChienVan01

Stories:
Link code feature: https://github.com/fabatek/onboarding-job-board-frontend/tree/feature/chientv/t03_add_pagination
Link deploy surge: https://delirious-seat.surge.sh/
Link API to see specific job totals: https://6239311d043817a543df0a3f.mockapi.io/api/jobs

Notes: 

1. Add SEARCH_FILTER type in JobsActionType.ts
2. Add case SEARCH_FILTER in JobReducer.ts
3. Edit Function GetJob() in JobsAction.ts
4. Add Loading button in JobList component

results
![image](https://user-images.githubusercontent.com/85722847/160745721-4a513d12-65a8-4baf-b65c-1c5cbbbe1a25.png)
![image](https://user-images.githubusercontent.com/85722847/160745782-e4cdd914-d890-44c5-9d67-d0ae7ae44c4c.png)

2022-03-30 07:30 UTC, ducdmfaba requested changes

2022-03-30 07:30 UTC, ducdmfaba commented on src/actions/JobsAction.ts
> +        `https://6239311d043817a543df0a3f.mockapi.io/api/jobs`
Please extract `https://6239311d043817a543df0a3f.mockapi.io/api` to constant.

2022-03-30 07:30 UTC, ducdmfaba commented on src/actions/JobsAction.ts
> +          });
Why did you use filter? I think the endpoint currently supported search functionality.

2022-03-30 07:30 UTC, ducdmfaba commented on src/components/jobList/JobList.tsx
> +    </div>
We should have a component `Loading`

2022-03-30 07:30 UTC, ducdmfaba commented on src/components/seachContainer/SearchContainer.tsx
> +  const [searchText, setSearchText] = useState('');
Missing data type.

2022-03-30 07:30 UTC, ducdmfaba commented on src/containers/Home/index.tsx
> +    dispatch(GetJob(''));
The function name should be `getJobs`

2022-03-30 07:30 UTC, ducdmfaba commented on src/containers/Home/index.tsx
>    console.log(jobState);
Remove test code.

2022-04-01 02:56 UTC, ducdmfaba commented
@ChienVan01 Please let me know when you have finished this.

2022-04-01 02:58 UTC, ChienVan01 commented
> @ChienVan01 Please let me know when you have finished this.

Sorry, I'll finish it today

2022-04-01 04:20 UTC, ducdmfaba requested changes

2022-04-01 04:20 UTC, ducdmfaba commented on src/actions/JobsAction.ts
> +      searchTitle === ''
Just `!!searchTitle`

2022-04-01 04:20 UTC, ducdmfaba commented on src/actions/JobsAction.ts
> +      const res = await axios.get(BASE_URL + `?name=${searchTitle}`);
- Please use `template string` for this. 
- When `searchTitle` is null, endpoint should be `BASE_URL` instead `BASE_URL?name=`

2022-04-01 04:20 UTC, ducdmfaba commented on src/actions/JobsAction.ts
> +              search: searchTitle,
Do we need to store `searchTitle`?

2022-04-01 04:20 UTC, ducdmfaba commented on src/components/jobList/JobList.tsx
> +    </>
Please extract this to the component. If we have existed, try to re-use it.

2022-04-01 04:20 UTC, ducdmfaba commented on src/components/searchContainer/SearchContainer.tsx
> +    console.log(e.target.value);
Remove test code.

2022-04-01 04:20 UTC, ducdmfaba commented on src/containers/Home/index.test.tsx
> +    const result = await axios.get(BASE_URL + `?name=${itemSearch}`);
`template string`

2022-04-01 04:20 UTC, ducdmfaba commented on src/containers/Home/index.tsx
> +    dispatch(getJob(''));
No need empty string for argument here.

2022-04-01 06:20 UTC, ducdmfaba requested changes

2022-04-01 06:20 UTC, ducdmfaba commented on src/components/jobList/JobList.tsx
> +    </>
Please move it outside the component to reuse.

2022-04-01 06:33 UTC, ducdmfaba commented on src/actions/JobsAction.ts
> +      const res = await axios.get(BASE_URL + `?name=${searchTitle}`);
Is it fixed?

2022-04-01 06:35 UTC, ducdmfaba requested changes

2022-04-01 06:35 UTC, ducdmfaba commented on src/components/jobList/JobList.tsx
> +
I mean you should create it in components folders.

2022-04-01 08:26 UTC, ducdmfaba requested changes

2022-04-01 08:26 UTC, ducdmfaba commented on src/components/searchContainer/SearchContainer.tsx
> +    return setSearchText(e.target.value);
Why did you use function return for this?

2022-04-01 08:26 UTC, ducdmfaba commented on src/components/jobList/JobList.tsx
> +    </div>
This does not make sense. 
- I don't think `job` can be null.
- In javascript or typescript avoid equaling by `==`. 
Please remove it.

2022-04-01 09:22 UTC, ducdmfaba approved these changes

2022-04-01 09:22 UTC, merged